-- MySQL Script generated by MySQL Workbench
-- Sun Apr 11 23:11:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banks_crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banks_crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banks_crm` DEFAULT CHARACTER SET utf8 ;
USE `banks_crm` ;

-- -----------------------------------------------------
-- Table `banks_crm`.`clients_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`clients_profiles` (
  `id_client` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password_hash` VARCHAR(65) NULL,
  `date_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_deleted` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`clients_passports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`clients_passports` (
  `id_client` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(65) NOT NULL,
  `patronymic` VARCHAR(65) NOT NULL,
  `last_name` VARCHAR(65) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `birthday` DATE NOT NULL,
  `birth_place` VARCHAR(255) NOT NULL,
  `passport_number` BIGINT(10) NOT NULL,
  `issue_date` DATE NOT NULL,
  `issue_department` VARCHAR(255) NOT NULL,
  `issue_department_code` CHAR(7) NOT NULL,
  `place_of_residence` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_client`),
  FULLTEXT INDEX `full_name` (`first_name`, `patronymic`, `last_name`) INVISIBLE,
  INDEX `passport_number` (`passport_number` ASC) VISIBLE,
  UNIQUE INDEX `passport_number_UNIQUE` (`passport_number` ASC) VISIBLE,
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_clients_passports_clients_profiles`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`clients_resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`clients_resume` (
  `id_client` INT UNSIGNED NOT NULL,
  `rating` INT UNSIGNED NOT NULL DEFAULT 10000,
  `family_client` TINYINT NULL,
  `salary_client` TINYINT NULL,
  `staff_client` TINYINT NULL,
  `id_advertisement_group` INT UNSIGNED NULL,
  PRIMARY KEY (`id_client`),
  INDEX `advertisement_group` (`id_advertisement_group` ASC) VISIBLE,
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_table1_clients_profiles1`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`client_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`client_contacts` (
  `id_client` INT UNSIGNED NOT NULL,
  `phone_number` VARCHAR(20) NULL,
  `phone_number_additional` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  `place_of_residence` VARCHAR(500) NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_additional_UNIQUE` (`phone_number_additional` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_table1_clients_profiles2`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`client_social_networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`client_social_networks` (
  `id_client` INT UNSIGNED NOT NULL,
  `url_social_network` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_client`, `url_social_network`),
  UNIQUE INDEX `url_social_network_UNIQUE` (`url_social_network` ASC) VISIBLE,
  CONSTRAINT `fk_table1_clients_profiles3`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`offers_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`offers_credit` (
  `id_offer_credit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `duration_max` SMALLINT(4) UNSIGNED NOT NULL,
  `duration_min` SMALLINT(4) UNSIGNED NOT NULL,
  `limit_min` DECIMAL(12,2) UNSIGNED NOT NULL,
  `limit_max` DECIMAL(12,2) UNSIGNED NOT NULL,
  `interest_rate` DECIMAL(5,2) UNSIGNED NOT NULL,
  `payment_period` SMALLINT(4) UNSIGNED NOT NULL,
  `insurance` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(65) NOT NULL,
  `date_start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_stop` DATETIME NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`id_offer_credit`),
  INDEX `duration_max` (`duration_max` ASC) VISIBLE,
  INDEX `duration_min` (`duration_min` ASC) INVISIBLE,
  INDEX `limit_max` (`limit_max` ASC) VISIBLE,
  INDEX `limit_min` (`limit_min` ASC) VISIBLE,
  INDEX `interest_rate` (`interest_rate` ASC) VISIBLE,
  INDEX `date_start` (`date_start` ASC) VISIBLE,
  INDEX `date_stop` (`date_stop` ASC) VISIBLE,
  UNIQUE INDEX `id_offer_credit_UNIQUE` (`id_offer_credit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`accounts_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`accounts_credit` (
  `id_account_credit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_offer_credit` INT UNSIGNED NOT NULL,
  `id_client` INT UNSIGNED NOT NULL,
  `date_start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_stop` DATETIME NOT NULL,
  `modifier` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `account_number` BIGINT(20) UNSIGNED NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`id_account_credit`),
  INDEX `fk_accounts_credit_offers_credit1_idx` (`id_offer_credit` ASC) VISIBLE,
  INDEX `fk_accounts_credit_clients_profiles1_idx` (`id_client` ASC) VISIBLE,
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC) VISIBLE,
  INDEX `date_start` (`date_start` ASC) INVISIBLE,
  INDEX `date_stop` (`date_stop` ASC) VISIBLE,
  UNIQUE INDEX `id_account_credit_UNIQUE` (`id_account_credit` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_credit_offers_credit1`
    FOREIGN KEY (`id_offer_credit`)
    REFERENCES `banks_crm`.`offers_credit` (`id_offer_credit`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_accounts_credit_clients_profiles1`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`accounts_credit_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`accounts_credit_status` (
  `id_account_credit` INT UNSIGNED NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `debt` DECIMAL(12,2) UNSIGNED NOT NULL,
  `debt_interest` DECIMAL(12,2) UNSIGNED NOT NULL,
  `amount_of_delay` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_accounts_credit_status_accounts_credit1_idx` (`id_account_credit` ASC) VISIBLE,
  PRIMARY KEY (`id_account_credit`, `timestamp`),
  INDEX `debt` (`debt` ASC) INVISIBLE,
  INDEX `debt_interest` (`debt_interest` ASC) VISIBLE,
  INDEX `amount_of_delay` (`amount_of_delay` ASC) VISIBLE,
  INDEX `timestamp` (`timestamp` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_credit_status_accounts_credit1`
    FOREIGN KEY (`id_account_credit`)
    REFERENCES `banks_crm`.`accounts_credit` (`id_account_credit`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`offers_debit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`offers_debit` (
  `id_offer_debit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `duration_min` SMALLINT(4) UNSIGNED NOT NULL,
  `duration_max` SMALLINT(4) UNSIGNED NOT NULL,
  `limit_min` DECIMAL(12,2) UNSIGNED NOT NULL,
  `limit_max` DECIMAL(12,2) UNSIGNED NOT NULL,
  `profitability` DECIMAL(5,2) UNSIGNED NOT NULL,
  `accrual_period` SMALLINT(4) UNSIGNED NOT NULL,
  `insurance` DECIMAL(12,2) UNSIGNED NOT NULL,
  `deposit` TINYINT NOT NULL DEFAULT 1,
  `withdraw` TINYINT NOT NULL DEFAULT 1,
  `name` VARCHAR(65) NOT NULL,
  `date_start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_stop` DATETIME NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`id_offer_debit`),
  INDEX `duration_max` (`duration_max` ASC) INVISIBLE,
  INDEX `duration_min` (`duration_min` ASC) INVISIBLE,
  INDEX `limit_max` (`limit_max` ASC) INVISIBLE,
  INDEX `limit_min` (`limit_min` ASC) VISIBLE,
  INDEX `profitability` (`profitability` ASC) INVISIBLE,
  INDEX `date_start` (`date_start` ASC) INVISIBLE,
  INDEX `date_stop` (`date_stop` ASC) VISIBLE,
  UNIQUE INDEX `id_offer_debit_UNIQUE` (`id_offer_debit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`accounts_debit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`accounts_debit` (
  `id_account_debit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_offer_debit` INT UNSIGNED NOT NULL,
  `id_client` INT UNSIGNED NOT NULL,
  `date_start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_stop` DATETIME NULL,
  `modifier` DECIMAL(5,2) UNSIGNED NOT NULL DEFAULT 0,
  `account_number` BIGINT(20) UNSIGNED NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (`id_account_debit`),
  INDEX `fk_accounts_debit_offers_debit1_idx` (`id_offer_debit` ASC) VISIBLE,
  INDEX `fk_accounts_debit_clients_profiles1_idx` (`id_client` ASC) VISIBLE,
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC) VISIBLE,
  INDEX `date_start` (`date_start` ASC) INVISIBLE,
  INDEX `date_stop` (`date_stop` ASC) VISIBLE,
  UNIQUE INDEX `id_account_debit_UNIQUE` (`id_account_debit` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_debit_offers_debit1`
    FOREIGN KEY (`id_offer_debit`)
    REFERENCES `banks_crm`.`offers_debit` (`id_offer_debit`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_accounts_debit_clients_profiles1`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`account_debit_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`account_debit_status` (
  `accounts_debit_id_account_debit` INT UNSIGNED NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `balance` DECIMAL(12,2) NULL,
  INDEX `fk_table1_accounts_debit1_idx` (`accounts_debit_id_account_debit` ASC) INVISIBLE,
  PRIMARY KEY (`accounts_debit_id_account_debit`, `timestamp`),
  INDEX `balance` (`balance` ASC) VISIBLE,
  INDEX `timestamp` (`timestamp` ASC) VISIBLE,
  CONSTRAINT `fk_table1_accounts_debit1`
    FOREIGN KEY (`accounts_debit_id_account_debit`)
    REFERENCES `banks_crm`.`accounts_debit` (`id_account_debit`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`clients_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`clients_sessions` (
  `id_clients_session` INT UNSIGNED NOT NULL,
  `id_client` INT UNSIGNED NOT NULL,
  `id_staff` INT UNSIGNED NULL,
  `date_start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_stop` DATETIME NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `id_type` INT UNSIGNED NULL,
  `ip_v4` INT UNSIGNED NULL,
  `phone_number` VARCHAR(20) NULL,
  PRIMARY KEY (`id_clients_session`),
  INDEX `fk_clients_sessions_clients_profiles1_idx` (`id_client` ASC) INVISIBLE,
  INDEX `date_start` (`date_start` ASC) INVISIBLE,
  INDEX `date_stop` (`date_stop` ASC) VISIBLE,
  UNIQUE INDEX `id_clients_session_UNIQUE` (`id_clients_session` ASC) VISIBLE,
  CONSTRAINT `fk_clients_sessions_clients_profiles1`
    FOREIGN KEY (`id_client`)
    REFERENCES `banks_crm`.`clients_profiles` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banks_crm`.`clients_operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banks_crm`.`clients_operations` (
  `id_clients_operation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_clients_session` INT UNSIGNED NOT NULL,
  `timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `amount_of_money` DECIMAL(12,2) UNSIGNED NOT NULL,
  `account_number_from` BIGINT(20) UNSIGNED NOT NULL,
  `account_number_to` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_clients_operation`),
  INDEX `fk_clients_operations_clients_sessions1_idx` (`id_clients_session` ASC) VISIBLE,
  INDEX `timestamp` (`timestamp` ASC) INVISIBLE,
  INDEX `amount_of_money` (`amount_of_money` ASC) VISIBLE,
  UNIQUE INDEX `id_clients_operation_UNIQUE` (`id_clients_operation` ASC) VISIBLE,
  CONSTRAINT `fk_clients_operations_clients_sessions1`
    FOREIGN KEY (`id_clients_session`)
    REFERENCES `banks_crm`.`clients_sessions` (`id_clients_session`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
